from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^dateapi/$', 'LifeApi.views.DateApi'),   
    url(r'^catapi/$', 'LifeApi.views.CatApi'),       
    url(r'^homeapi/$', 'LifeApi.views.HomeApi', ),      
    url(r'^eventapi/$', 'LifeApi.views.EventApi'),   
    url(r'^eventinfoapi/$', 'LifeApi.views.EventInfoApi'),   
    url(r'^searchkey/$', 'LifeApi.views.SearchKey'),   
    url(r'^tag_hot/$','LifeApi.views.tag_hot'),
    url(r'^custom_message/$','LifeApi.views.CustomMessage'),
    url(r'^searchorder/$','LifeApi.views.searchOrder'),    
    url(r'^submitorder/$','LifeApi.views.submitOrder'),
    url(r'^collectevent/(\d+?)/$','LifeApi.views.collect'),
    url(r'^collectevent_del/$','LifeApi.views.collect_del'),
    url(r'^app/(.*?)$','LifeApi.views.downloadapp'),
    url(r'^send_msg_text/$','LifeApi.views.send_msg_text'),
    url(r'^previous_api/$','LifeApi.views.PreviousEventApi'),
    url(r'delorder/$','LifeApi.views.delOrder'),
    url(r'^dateapi_T/$', 'LifeApi.views.DateApiT'),
    url(r'^cityapi/$', 'LifeApi.views.CityApi', ),
    url(r'^searchgeo/$', 'LifeApi.search_geo.search_geo'),
    url(r'^submitorder_weixin/$','LifeApi.views.submitOrder_weixin'),
    url(r'^getimg/$', 'LifeApi.views.get_img'),
    url(r'^app_push/$', 'LifeApi.app_push.basic_push'),
    url(r'^getcurrency/$','LifeApi.views.getRMB',name='api_getCurrency'),
)
